import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { isLoggedIn } from '@/db/lib/auth'
import Header1 from '@/components/navbar/Header1'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const authStatus: boolean = isLoggedIn();
 
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header1 isLoggedIn={authStatus}/>
        {children}
        
      </body>
    </html>
  )
}
